package com.candbright.onestop.dao;

import java.util.List;
import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;
import org.greenrobot.greendao.query.Query;
import org.greenrobot.greendao.query.QueryBuilder;

import com.candbright.onestop.common.bean.SongComment;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "SONG_COMMENT".
*/
public class SongCommentDao extends AbstractDao<SongComment, Long> {

    public static final String TABLENAME = "SONG_COMMENT";

    /**
     * Properties of entity SongComment.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property SongId = new Property(1, int.class, "songId", false, "SONG_ID");
        public final static Property Content = new Property(2, String.class, "content", false, "CONTENT");
        public final static Property Date = new Property(3, int.class, "date", false, "DATE");
        public final static Property Likes = new Property(4, int.class, "likes", false, "LIKES");
        public final static Property CommentId = new Property(5, int.class, "commentId", false, "COMMENT_ID");
    }

    private Query<SongComment> song_CommentsQuery;

    public SongCommentDao(DaoConfig config) {
        super(config);
    }
    
    public SongCommentDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"SONG_COMMENT\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"SONG_ID\" INTEGER NOT NULL ," + // 1: songId
                "\"CONTENT\" TEXT," + // 2: content
                "\"DATE\" INTEGER NOT NULL ," + // 3: date
                "\"LIKES\" INTEGER NOT NULL ," + // 4: likes
                "\"COMMENT_ID\" INTEGER NOT NULL );"); // 5: commentId
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"SONG_COMMENT\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, SongComment entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getSongId());
 
        String content = entity.getContent();
        if (content != null) {
            stmt.bindString(3, content);
        }
        stmt.bindLong(4, entity.getDate());
        stmt.bindLong(5, entity.getLikes());
        stmt.bindLong(6, entity.getCommentId());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, SongComment entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getSongId());
 
        String content = entity.getContent();
        if (content != null) {
            stmt.bindString(3, content);
        }
        stmt.bindLong(4, entity.getDate());
        stmt.bindLong(5, entity.getLikes());
        stmt.bindLong(6, entity.getCommentId());
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public SongComment readEntity(Cursor cursor, int offset) {
        SongComment entity = new SongComment( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getInt(offset + 1), // songId
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // content
            cursor.getInt(offset + 3), // date
            cursor.getInt(offset + 4), // likes
            cursor.getInt(offset + 5) // commentId
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, SongComment entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setSongId(cursor.getInt(offset + 1));
        entity.setContent(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setDate(cursor.getInt(offset + 3));
        entity.setLikes(cursor.getInt(offset + 4));
        entity.setCommentId(cursor.getInt(offset + 5));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(SongComment entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(SongComment entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(SongComment entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
    /** Internal query to resolve the "comments" to-many relationship of Song. */
    public List<SongComment> _querySong_Comments(int songId) {
        synchronized (this) {
            if (song_CommentsQuery == null) {
                QueryBuilder<SongComment> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.SongId.eq(null));
                song_CommentsQuery = queryBuilder.build();
            }
        }
        Query<SongComment> query = song_CommentsQuery.forCurrentThread();
        query.setParameter(0, songId);
        return query.list();
    }

}
